language: node_js
node_js:
  - 8.14.1
branches:
  only:
    - master
    - /^publish.*$/
before_install: node -v && npm -v && npm config ls -g
install: yarn
script: 
  - if [$TRAVIS_BRANCH = master]; then npm run build; fi
  - if [$TRAVIS_BRANCH =~ ^publish.*$]; then yarn config list; fi
