language: node_js
node_js:
  - "8.14.1"
branches:
  only:
    - master
    - /^publish*$/
before_install: node -v && npm -v && npm config ls -g
install: yarn
script: npm run build
deploy:
  provider: script
  script: npm publish
  skip_cleanup: true
  on:
    branch: /^publish*$/
    tags: false
