language: node_js
node_js:
  - 8.14.1
branches:
  only:
    - master
    - /^publish.*$/
before_install: node -v && npm -v && npm config ls -g
install: yarn
script: npm run build
deploy:
  provider: npm
  email: csuhlb@gmail.com
  api_key: $API_TOKEN
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^publish.*$
    tags: false
